# yaml文件，文件名为yamlData

# 用于生成admin账户的用户名，昵称和密码
admin:
  username: admin_123
  nickname: admin_123
  password: admin_123

# 用于生成编辑账户的用户名，昵称和密码
editor:
  username: editor_123
  nickname: editor_123
  password: editor_123

# 用于生成一个普通账户的用户名，昵称和密码
user:
  username: user_123
  nickname: user_123
  password: user_123

database:
  SQLALCHEMY_DATABASE_URI:  mysql://root:Woniunote123456@localhost:3306/woniunote?charset=utf8&autocommit=true

# 配置文章类型
ARTICLE_TYPES:
  1: 量化思考
  2: 量化框架
  3: 交易策略
  4: 股票
  5: 期货
  6: 期权
  7: 基金
  8: 债券
  9: 理财
  10: 保险
  11: 学习与感悟
  12: 公益