# yaml文件，文件名为config.yaml

# 用于生成admin账户的用户名，昵称和密码
admin:
  username: administrator
  nickname: yunjinqi
  password: high_gold_course

# 用于生成编辑账户的用户名，昵称和密码
editor:
  username: yunjinqi@qq.com
  nickname: yunjinqi
  password: yunjinqi2015

# 用于生成一个普通账户的用户名，昵称和密码
user:
  username: yunjinqi
  nickname: yunjinqi
  password: iamyunjinqi

database:
  SQLALCHEMY_DATABASE_URI: mysql://woniunote_user:Woniunote_password1!@localhost:3306/woniunote?charset=utf8&autocommit=true

# 配置文章类型
ARTICLE_TYPES:
  1: 量化思考
  2: 量化框架
  3: 交易策略
  4: 股票
  5: 期货
  6: 期权
  7: 基金
  8: 债券
  9: 理财
  10: 保险
  11: 学习与感悟
  12: 公益