# 配置文章类型
ARTICLE_TYPES:
  1: 交易策略
  11: CTA策略
  12: 统计套利
  13: 高频交易
  14: 因子策略
  15: 选股与择时
  16: 机器学习
  17: 深度学习

  2: 量化框架
  21: backtrader
  22: wondertrader
  23: wtpy
  24: pyfolio
  25: alphalens

  3: 投资资产
  31: 股票
  32: 期货
  33: 期权
  34: 外汇
  35: crypto
  4: 理财资产
  41: 基金
  42: 保险
  43: 信托
  44: 银行理财
  45: 存款
  5: 区块链与defi
  51: 去中心化交易所
  52: 去中心化金融
  53: 去中心化借贷
  54: 去中心化治理
  55: 其他defi
  56: 区块链
  57: 比特币
  58: 以太坊
  6: 机器学习
  61: tensorflow
  62: pytorch
  63: keras
  64: sklearn
  65: 机器学习与交易
  7: 编程语言
  71: python
  72: c++
  73: cython
  74: java
  75: javascript
  76: cython
  77: pybind11
  78: swing
  8: 笔记
  81: 幸福
  82: 金融
  83: 经济
  84: 哲学
  85: 历史
  86: 科技
  9: 公益信息
  91: woniunote入门教程
  92: backtrader基础教程
  93: airflow入门教程
  94: arrow入门教程
  95: 量化交易入门教程
  96: 机器学习入门教程
  97: ib_tws_api入门教程